// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjhJa_XohBIGiIMeKsM1A_GMH_pHE4yk',
    appId: '1:771663024305:web:6ce7e4936580bbd94c5290',
    messagingSenderId: '771663024305',
    projectId: 'integracion-8b736',
    authDomain: 'integracion-8b736.firebaseapp.com',
    databaseURL: 'https://integracion-8b736-default-rtdb.firebaseio.com',
    storageBucket: 'integracion-8b736.firebasestorage.app',
    measurementId: 'G-HCVPWL3J3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfYMFB3lDyT9DcjdrQH-PvmTxuMhlVFn4',
    appId: '1:771663024305:android:ec7e7855888cd0984c5290',
    messagingSenderId: '771663024305',
    projectId: 'integracion-8b736',
    databaseURL: 'https://integracion-8b736-default-rtdb.firebaseio.com',
    storageBucket: 'integracion-8b736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGU7KakkHpmSjV7Or3DTg0tcQUC1fua9k',
    appId: '1:771663024305:ios:91e261562e6d73af4c5290',
    messagingSenderId: '771663024305',
    projectId: 'integracion-8b736',
    databaseURL: 'https://integracion-8b736-default-rtdb.firebaseio.com',
    storageBucket: 'integracion-8b736.firebasestorage.app',
    iosBundleId: 'com.example.firabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGU7KakkHpmSjV7Or3DTg0tcQUC1fua9k',
    appId: '1:771663024305:ios:91e261562e6d73af4c5290',
    messagingSenderId: '771663024305',
    projectId: 'integracion-8b736',
    databaseURL: 'https://integracion-8b736-default-rtdb.firebaseio.com',
    storageBucket: 'integracion-8b736.firebasestorage.app',
    iosBundleId: 'com.example.firabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChjhJa_XohBIGiIMeKsM1A_GMH_pHE4yk',
    appId: '1:771663024305:web:b480c9923de1a7b84c5290',
    messagingSenderId: '771663024305',
    projectId: 'integracion-8b736',
    authDomain: 'integracion-8b736.firebaseapp.com',
    databaseURL: 'https://integracion-8b736-default-rtdb.firebaseio.com',
    storageBucket: 'integracion-8b736.firebasestorage.app',
    measurementId: 'G-YMKB6WJGPM',
  );

}